# Theme gruvbox
set -g @plugin 'tmux-plugins/tmux-sensible' # optional recommended
set -g @plugin 'egel/tmux-gruvbox'
# set desired theme options...
set -g @tmux-gruvbox 'dark' # or 'dark256', 'light', 'light256'
